name: Go Unit Tests
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Install Dependencies
        run: go get ./...
      - name: Test with Go CLI
        run: go test ./...
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/server
        
      
